### ISSUE TITLE
No template found!

### ISSUE THREAD

**Issue by gibbs** [PhileCMS/phileTemplateSmarty#1]
What's up with: 

``` php
$output = 'No template found!';
```

https://github.com/PhileCMS/phileTemplateSmarty/blob/master/Classes/Smarty.php#L41

Is that meant to be there?

**Comment by Schlaefer** [comment]
Hi, thanks for the feedback. Alas nobody is maintaining this repository at the moment.

I close this issue as I mark this repository as abandoned and archived.
